on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
        flutter-version: '3.x'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --output-dir=./

    - name: Upload APK
      uses: actions/upload-artifact@v4.3.1
      with:
        name: signwave-apk
        path: signwave.apk

