name: Unit-Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r signwave_api/requirements.txt # Install your project dependencies

    - name: Run tests
      run: |
        python -m pytest # Run your pytest unit tests
